---
title: "twitter_following_network"
author: "Shuai"
date: '2022-05-21'
output: html_document
---

```{r}
twitter <- read.csv("twitter-following.csv")
senator <- read.csv("twitter-senator.csv")
```

```{r}
n <- nrow(senator)

twitter.adj <- matrix(0, nrow = n, ncol = n)
colnames(twitter.adj) <- rownames(twitter.adj) <- senator$screen_name

for (i in 1:nrow(twitter)) {
  twitter.adj[twitter$following[i], twitter$followed[i]] <- 1
}
```

```{r}
twitter.adj <- graph.adjacency(twitter.adj, mode = "directed", diag = FALSE)
```

```{r}
senator$indegree <- degree(twitter.adj, mode = "in")
senator$outdegree <- degree(twitter.adj, mode = "out")
```

```{r}
in.order <- order(senator$indegree, decreasing = TRUE)
out.order <- order(senator$outdegree, decreasing = TRUE)
```

```{r}
senator[in.order[1:3],]
```

```{r}
senator[out.order[1:3],]
```

```{r}
n <- nrow(senator)

col <- rep("red", n)
col[senator$party == "D"] <- "blue"
col[senator$party == "I"] <- "black"

pch <- rep(16, n)
pch[senator$party == "D"] <- 17
pch[senator$party == "I"] <- 4

plot(closeness(twitter.adj, mode = "in"), closeness(twitter.adj, mode = "out"), pch = pch, col = col, main = "Closeness", xlab = "Incoming path", ylab = "Outgoing path")
plot(betweenness(twitter.adj, directed = TRUE), betweenness(twitter.adj, directed = TRUE), pch = pch, col = col, main = "Betweenness", xlab = "Directed", ylab = "Undirected")
```

```{r}
senator$pagerank <- page.rank(twitter.adj)$vector
```

```{r}
plot(twitter.adj, vertex.size = senator$pagerank * 1000, vertex.color = col, vertex.label = NA, edge.arrow.size = 0.1, edge.width = 0.5)
```


