---
title: "tutorial"
author: "Shuai"
date: '2022-06-11'
output: html_document
---

```{r}
sims <- 1000
guess <- c("M", "T", "T", "M", "M", "T", "T", "M")
correct <- rep(NA, sims)
for (i in 1:sims) {
  cups <- sample(c(rep("T", 4), rep("M", 4)), replace = FALSE)
  correct[i] <- sum(guess == cups)
}
prop.table(table(correct))
```

```{r}
x <- matrix(c(4, 0, 0, 4), byrow = TRUE, ncol = 2, nrow = 2)
y <- matrix(c(3, 1, 1, 3), byrow = TRUE, ncol = 2, nrow = 2)
```

```{r}
x
```

```{r}
y
```

```{r}
fisher.test(x, alternative = "greater")
```

```{r}
fisher.test(y)
```

```{r}
n <- 1018
x.bar <- 550 / n
se <- sqrt(0.5 * 0.5 / n)
upper <- pnorm(x.bar, mean = 0.5, sd = se, lower.tail = FALSE)
lower <- pnorm(0.5 - (x.bar - 0.5), mean = 0.5, sd = se)
upper + lower
```

```{r}
2 * upper
```

```{r}
upper
```

```{r}
z.score <- (x.bar - 0.5) / se
z.score
```

```{r}
pnorm(z.score, lower.tail = FALSE)
```

```{r}
2 * pnorm(z.score, lower.tail = FALSE)
```

```{r}
c(x.bar - qnorm(0.995) * se, x.bar + qnorm(0.995) * se)
```

```{r}
c(x.bar - qnorm(0.975) * se, x.bar + qnorm(0.975) * se)
```

```{r}
prop.test(550, n = n, p = 0.5, correct = FALSE)
```

```{r}
prop.test(550, n = n, p = 0.5)
```

```{r}
prop.test(550, n = n, p = 0.5, conf.level = 0.99)
```

```{r}
t.test(STAR$g4reading, mu = 710)
```

```{r}
pnorm(-abs(ate.est), mean = 0, sd = ate.se)
```

```{r}
2 * pnorm(-abs(ate.est), mean = 0, sd = ate.se)
```

```{r}
t.test(STAR$g4reading[STAR$classtype == 1], STAR$g4reading[STAR$classtype == 2])
```

```{r}
resume <- read.csv("resume.csv")
x <- table(resume$race, resume$call)
```

```{r}
x
```

```{r}
prop.test(x, alternative = "greater")
```

```{r}
n0 <- sum(resume$race == "black")
n1 <- sum(resume$race == "white")
p <- mean(resume$call)
p0 <- mean(resume$call[resume$race == "black"])
p1 <- mean(resume$call[resume$race == "white"])
```

```{r}
est <- p1 - p0
est
```

```{r}
se <- sqrt(p * (1 - p) * (1 / n0 + 1 / n1))
se
```

```{r}
zstat <- est / se
zstat
```

```{r}
pnorm(-abs(zstat))
```

```{r}
prop.test(x, alternative = "greater", correct = FALSE)
```


