---
title: "tutorial"
author: "Shuai"
date: '2022-05-24'
output: html_document
---

```{r}
dunif(0.5, min = 0, max = 1)
```

```{r}
punif(1, min = -2, max = 2)
```

```{r}
sims <- 1000
p <- 0.5
x <- runif(sims, min = 0, max = 1)
head(x)
```

```{r}
y <- as.integer(x <= p)
head(y)
```

```{r}
mean(y)
```

```{r}
dbinom(2, size = 3, prob = 0.5)
```

```{r}
pbinom(1, size = 3, prob = 0.5)
```

```{r}
voters <- c(1000, 10000, 100000)
dbinom(voters / 2, size = voters, prob = 0.5)
```

```{r}
pnorm(1) - pnorm(-1)
```

```{r}
pnorm(2) - pnorm(-2)
```

```{r}
mu <- 5
sigma <- 2
pnorm(mu + sigma, mean = mu, sd = sigma) - pnorm(mu - sigma, mean = mu, sd = sigma)
```

```{r}
pnorm(mu + 2*sigma, mean = mu, sd = sigma) - pnorm(mu - 2*sigma, mean = mu, sd = sigma)
```

```{r}
sims <- 1000
x.binom <- rbinom(sims, p = 0.2, size = 10)
mean.binom <- cumsum(x.binom) / 1:sims
```

```{r}
x.unif <- runif(sims)
mean.unif <- cumsum(x.unif) / 1:sims
```

```{r}
plot(1:sims, mean.binom, type = "l", ylim = c(1, 3), xlab = "Sample size", ylab = "Sample mean", main = "Binomial(10, 0.2)")
abline(h = 2, lty = "dashed")
```

```{r}
plot(1:sims, mean.unif, type = "l", ylim = c(0, 1), xlab = "Sample size", ylab = "Sample mean", main = "Uniform(0, 1)")
abline(h = 0.5, lty = "dashed")
```

```{r}
n.samp <- 1000
z.binom <- z.unif <- rep(NA, sims)

for (i in 1:sims) {
  x <- rbinom(n.samp, p = 0.2, size = 10)
  z.binom[i] <- (mean(x) - 2) / sqrt(1.6 / n.samp)
  x <- runif(n.samp, min = 0, max = 1)
  z.unif[i] <- (mean(x) - 0.5) / sqrt(1 / (12 * n.samp))
}

hist(z.binom, freq = FALSE, nclass = 40, xlim = c(-4, 4), ylim = c(0, 0.6), xlab = "z-score", main = "Binomial(0.2, 10)")
x <- seq(from = -3, to = 3, by = 0.01)
lines(x, dnorm(x))
```

```{r}
hist(z.unif, freq = FALSE, nclass = 40, xlim = c(-4, 4), ylim = c(0, 0.6), xlab = "z-score", main = "Unifor(0, 1)")
lines(x, dnorm(x))
```


