---
title: "minwage"
author: "Shuai"
date: '2022-05-16'
output: html_document
---

```{r}
minwage <- read.csv("minwage.csv")
dim(minwage)
```

```{r}
summary(minwage)
```

```{r}
minwageNJ <- subset(minwage, subset = (location != "PA"))
minwagePA <- subset(minwage, subset = (location == "PA"))
```

```{r}
mean(minwageNJ$wageBefore < 5.05)
```

```{r}
mean(minwageNJ$wageAfter < 5.05)
```

```{r}
mean(minwagePA$wageBefore < 5.05)
```

```{r}
mean(minwagePA$wageAfter < 5.05)
```

```{r}
minwageNJ$fullPropAfter <- minwageNJ$fullAfter / (minwageNJ$fullAfter + minwageNJ$partAfter)
minwagePA$fullPropAfter <- minwagePA$fullAfter / (minwagePA$fullAfter + minwagePA$partAfter)

mean(minwageNJ$fullPropAfter) - mean(minwagePA$fullPropAfter)
```

```{r}
prop.table(table(minwageNJ$chain))
```

```{r}
prop.table(table(minwagePA$chain))
```

```{r}
minwageNJ.bk <- subset(minwageNJ, subset = (chain == "burgerking"))
minwagePA.bk <- subset(minwagePA, subset = (chain == "burgerking"))
```

```{r}
mean(minwageNJ.bk$fullPropAfter) - mean(minwagePA.bk$fullPropAfter)
```

```{r}
minwageNJ.bk.subset <- subset(minwageNJ.bk, subset = ((location != "shoreNJ") & (location != "centralNJ")))
mean(minwageNJ.bk.subset$fullPropAfter) - mean(minwagePA.bk$fullPropAfter)
```

```{r}
minwageNJ$fullPropBefore <- minwageNJ$fullBefore / (minwageNJ$fullBefore + minwageNJ$partBefore)
```

```{r}
NJdiff <- mean(minwageNJ$fullPropAfter) - mean(minwageNJ$fullPropBefore)
NJdiff
```

```{r}
minwagePA$fullPropBefore <- minwagePA$fullBefore / (minwagePA$fullBefore + minwagePA$partBefore)
```

```{r}
PAdiff <- mean(minwagePA$fullPropAfter) - mean(minwagePA$fullPropBefore)
```

```{r}
NJdiff - PAdiff
```

```{r}
median(minwageNJ$fullPropAfter) - median(minwagePA$fullPropAfter)
```

```{r}
NJdiff.med <- median(minwageNJ$fullPropAfter) - median(minwageNJ$fullPropBefore)
NJdiff.med
```

```{r}
PAdiff.med <- median(minwagePA$fullPropAfter) - median(minwagePA$fullPropBefore)
PAdiff.med
```

```{r}
NJdiff.med - PAdiff.med
```

```{r}
summary(minwageNJ$wageBefore)
```

```{r}
summary(minwageNJ$wageAfter)
```

```{r}
IQR(minwageNJ$wageBefore)
```

```{r}
IQR(minwageNJ$wageAfter)
```

```{r}
quantile(minwageNJ$wageBefore, probs = seq(from = 0, to = 1, by = 0.1))
```

```{r}
quantile(minwageNJ$wageAfter, probs = seq(from = 0, to = 1, by = 0.1))
```

```{r}
sqrt(mean((minwageNJ$fullPropAfter - minwageNJ$fullPropBefore)^2))
```

```{r}
mean(minwageNJ$fullPropAfter - minwageNJ$fullPropBefore)
```
```{r}
sd(minwageNJ$fullPropBefore)
```

```{r}
sd(minwageNJ$fullPropAfter)
```

```{r}
var(minwageNJ$fullPropBefore)
```

```{r}
var(minwageNJ$fullPropAfter)
```


