---
title: "florida_registered_voter"
author: "Shuai"
date: '2022-05-21'
output: html_document
---

```{r}
FLVoters <- read.csv("FLVoters.csv")
dim(FLVoters)
```

```{r}
FLVoters <- na.omit(FLVoters)
dim(FLVoters)
```

```{r}
margin.race <- prop.table(table(FLVoters$race))
margin.race
```

```{r}
margin.gender <- prop.table(table(FLVoters$gender))
margin.gender
```

```{r}
prop.table(table(FLVoters$race[FLVoters$gender == "f"]))
```

```{r}
joint.p <- prop.table(table(race = FLVoters$race, gender = FLVoters$gender))
joint.p
```

```{r}
rowSums(joint.p)
```

```{r}
colSums(joint.p)
```

```{r}
FLVoters$age.group <- NA
FLVoters$age.group[FLVoters$age <= 20] <- 1
FLVoters$age.group[FLVoters$age > 20 & FLVoters$age <= 40] <- 2
FLVoters$age.group[FLVoters$age > 40 & FLVoters$age <= 60] <- 3
FLVoters$age.group[FLVoters$age > 60] <- 4
```

```{r}
joint3 <- prop.table(table(race = FLVoters$race, age.group = FLVoters$age.group, gender = FLVoters$gender))
joint3
```

```{r}
margin.age <- prop.table(table(FLVoters$age.group))
margin.age
```

```{r}
joint3["black", 4, "f"] / margin.age[4]
```

```{r}
joint2 <- prop.table(table(age.group = FLVoters$age.group, gender = FLVoters$gender))
joint2
```

```{r}
joint2[4, "f"]
```

```{r}
joint3["black", 4, "f"] / joint2[4, "f"]
```

```{r}
plot(c(margin.race * margin.gender["f"]),
     c(joint.p[,"f"]),
     xlim = c(0, 0.4),
     ylim = c(0, 0.4),
     xlab = "P(race) * P(female)",
     ylab = "P(race and female)")
abline(0, 1)
```

```{r}
plot(c(joint3[, 4, "f"]),
     margin.race * margin.age[4] * margin.gender["f"],
     xlim = c(0, 0.3),
     ylim = c(0, 0.3),
     main = "Joint independence",
     xlab = "P(race and above 60 and female)",
     ylab = "P(race) * P(above 60) * P(female)")
abline(0, 1)
```

```{r}
plot(c(joint3[, 4, "f"]) / margin.gender["f"],
     (joint.p[, "f"] / margin.gender["f"]) * (joint2[4, "f"] / margin.gender["f"]),
     xlim = c(0, 0.3),
     ylim = c(0, 0.3),
     main = "Marginal independence",
     xlab = "P(race and above 60 | female)",
     ylab = "P(race | female) * P(above 60 | female)")
abline(0, 1)
```

```{r}
sims <- 1000
doors <- c("goat", "goat", "car")
result.switch <- result.noswitch <- rep(NA, sims)

for (i in 1:sims) {
  first <- sample(1:3, size = 1)
  result.noswitch[i] <- doors[first]
  remain <- doors[-first]
  monty <- sample((1:2)[remain == "goat"], size = 1)
  result.switch[i] <- remain[-monty]
}

mean(result.noswitch == "car")
mean(result.switch == "car")
```

```{r}
FLVoters <- FLVoters[!is.na(match(FLVoters$surname, cnames$surname)),]
dim(FLVoters)
```

```{r}
whites <- subset(FLVoters, subset = (race == "white"))
w.indx <- match(whites$surname, cnames$surname)
head(w.indx)
```

```{r}
vars <- c("pctwhite", "pctblack", "pctapi", "pcthispanic", "pctothers")
mean(apply(cnames[w.indx, vars], 1, max) == cnames$pctwhite[w.indx])
```

```{r}
blacks <- subset(FLVoters, subset = (race == "black"))
b.indx <- match(blacks$surname, cnames$surname)
mean(apply(cnames[b.indx, vars], 1, max) == cnames$pctblack[b.indx])
```

```{r}
hispanics <- subset(FLVoters, subset = (race == "hispanic"))
h.indx <- match(hispanics$surname, cnames$surname)
mean(apply(cnames[h.indx, vars], 1, max) == cnames$pcthispanic[h.indx])
```

```{r}
asians <- subset(FLVoters, subset = (race == "asian"))
a.indx <- match(asians$surname, cnames$surname)
mean(apply(cnames[a.indx, vars], 1, max) == cnames$pctapi[a.indx])
```

```{r}
indx <- match(FLVoters$surname, cnames$surname)
1 - mean(FLVoters$race[apply(cnames[indx, vars], 1, max) == cnames$pctwhite[indx]] == "white")
```

```{r}
1 - mean(FLVoters$race[apply(cnames[indx, vars], 1, max) == cnames$pctblack[indx]] == "black")
```

```{r}
1 - mean(FLVoters$race[apply(cnames[indx, vars], 1, max) == cnames$pcthispanic[indx]] == "hispanic")
```

```{r}
1 - mean(FLVoters$race[apply(cnames[indx, vars], 1, max) == cnames$pctapi[indx]] == "asian")
```

```{r}
FLCensus <- read.csv("FLCensusVTD.csv")
race.prop <- apply(FLCensus[, c("white", "black", "api", "hispanic", "others")], 2, weighted.mean, weights = FLCensus$total.pop)
race.prop
```

```{r}
total.count <- sum(cnames$count)
```

```{r}
cnames$name.white <- (cnames$pctwhite / 100) * (cnames$count / total.count) / race.prop["white"]
cnames$name.black <- (cnames$pctblack / 100) * (cnames$count / total.count) / race.prop["black"]
cnames$name.hispanic <- (cnames$pcthispanic / 100) * (cnames$count / total.count) / race.prop["hispanic"]
cnames$name.asian <- (cnames$pctapi / 100) * (cnames$count / total.count) / race.prop["api"]
cnames$name.others <- (cnames$pctothers / 100) * (cnames$count / total.count) / race.prop["others"]
```

```{r}
FLVoters <- merge(x = FLVoters, y = FLCensus, by = c("county", "VTD"), all = FALSE)
indx <- match(FLVoters$surname, cnames$surname)
FLVoters$name.residence <- cnames$name.white[indx] * FLVoters$white + cnames$name.black[indx] * FLVoters$black + cnames$name.hispanic[indx] * FLVoters$hispanic + cnames$name.asian[indx] * FLVoters$api + cnames$name.others[indx] * FLVoters$others
```

```{r}
FLVoters$pre.white <- cnames$name.white[indx] * FLVoters$white / FLVoters$name.residence
FLVoters$pre.black <- cnames$name.black[indx] * FLVoters$black / FLVoters$name.residence
FLVoters$pre.hispanic <- cnames$name.hispanic[indx] * FLVoters$hispanic / FLVoters$name.residence
FLVoters$pre.asian <- cnames$name.asian[indx] * FLVoters$api / FLVoters$name.residence
FLVoters$pre.others <- 1 - FLVoters$pre.white - FLVoters$pre.black - FLVoters$pre.hispanic - FLVoters$pre.asian
```

```{r}
vars1 <- c("pre.white", "pre.black", "pre.hispanic", "pre.asian", "pre.others")

whites <- subset(FLVoters, subset = (race == "white"))
mean(apply(whites[, vars1], 1, max) == whites$pre.white)

blacks <- subset(FLVoters, subset = (race == "black"))
mean(apply(blacks[, vars1], 1, max) == blacks$pre.black)

hispanics <- subset(FLVoters, subset = (race == "hispanic"))
mean(apply(hispanics[, vars1], 1, max) == hispanics$pre.hispanic)

asians <- subset(FLVoters, subset = (race == "asian"))
mean(apply(asians[, vars1], 1, max) == asians$pre.asian)
```

```{r}
cnames$pctblack[cnames$surname == "WHITE"]

summary(FLVoters$pre.black[FLVoters$surname == "WHITE"])
```

```{r}
1 - mean(FLVoters$race[apply(FLVoters[, vars1], 1, max) == FLVoters$pre.white] == "white")
```

```{r}
1 - mean(FLVoters$race[apply(FLVoters[, vars1], 1, max) == FLVoters$pre.black] == "black")
```

```{r}
1 - mean(FLVoters$race[apply(FLVoters[, vars1], 1, max) == FLVoters$pre.hispanic] == "hispanic")
```

```{r}
1 - mean(FLVoters$race[apply(FLVoters[, vars1], 1, max) == FLVoters$pre.asian] == "asian")
```


