---
title: "face"
author: "Shuai"
date: '2022-05-19'
output: html_document
---

```{r}
face <- read.csv("face.csv")
```


```{r}
face$d.share <- face$d.votes / (face$d.votes + face$r.votes)
face$r.share <- face$r.votes / (face$d.votes + face$d.votes)
face$diff.share <- face$d.share - face$r.share
```

```{r}
plot(face$d.comp, face$diff.share, pch = 16, col = ifelse(face$w.party == "R", "red", "blue"), xlim = c(0, 1), ylim = c(-1, 1), xlab = "Competence scores for Democrats", ylab = "Democratic margin in vote share", main = "Facial competence and vote share")
```

```{r}
cor(face$d.comp, face$diff.share)
```

```{r}
fit <- lm(diff.share ~ d.comp, data = face)
fit
```

```{r}
lm(face$diff.share ~ face$d.comp)
```

```{r}
coef(fit)
```

```{r}
head(fitted(fit))
```

```{r}
plot(face$d.comp, face$diff.share, xlim = c(0, 1.05), ylim = c(-1, 1), xlab = "Competence scores for Democrats", ylab = "Democratic margin in vote share", main = "Facial competence and vote share")
abline(fit)
abline(v = 0, lty = "dashed")
```

```{r}
epsilon.hat <- resid(fit)
sqrt(mean(epsilon.hat^2))
```


