---
title: "loops_and_statements"
author: "Shuai"
date: '2022-05-19'
output: html_document
---

```{r}
values <- c(2, 4, 6)
n <- length(values)
results <- rep(NA, n)
```

```{r}
for (i in 1:n) {
  results[i] <- values[i] * 2
  cat(values[i], "times 2 is equal to", results[i], "\n")
}
```

```{r}
data <- data.frame("a" = 1:2, "b" = c("hi", "hey"), "c" = 3:4)
results <- rep(NA, 3)
for (i in 1:3) {
  cat("iteration", i, "\n")
  results[i] <- median(data[,i])
}
results
```

```{r}
operation <- "add"
if (operation == "add") {
  cat("I will perform addition 4 + 4\n")
  4 + 4
}
```

```{r}
if (operation == "multiply") {
  cat("I will perform multiplication 4 * 4\n")
  4 * 4
}
```

```{r}
operation <- "multiply"

if (operation == "add") {
  cat("I will perform addition 4 + 4\n")
  4 + 4
} else {
  cat("I will perform multiplication 4 * 4\n")
  4 * 4
}
```

```{r}
operation <- "subtract"

if (operation == "add") {
  cat("I will perform addition 4 + 4\n")
  4 + 4
} else if (operation == "multiply") {
  cat("I will perform multiplication 4 * 4\n")
  4 * 4
} else {
  cat("“", operation, "” is invalid. Use either “add” or “multiply.”\n", sep = "")
}
```

```{r}
values <- 1:5
n <- length(values)
results <- rep(NA, n)

for (i in 1:n) {
  x <- values[i]
  r <- x %% 2
  if (r == 0) {
    cat(x, "is even and I will perform addition", x, "+", x, "\n")
    results[i] <- x + x
  } else {
    cat(x, "is odd and I will perform multiplication", x, "*", x, "\n")
    results[i] <- x * x
  }
}

results
```

```{r}
pres08 <- read.csv("pres08.csv")
polls08 <- read.csv("polls08.csv")
```

```{r}
polls08$margin <- polls08$Obama - polls08$McCain
pres08$margin <- pres08$Obama - pres08$McCain
```

```{r}
polls08$middate <- as.Date(polls08$middate)
polls08$DaysToElection <- as.Date("2008-11-04") - polls08$middate
poll.pred <- rep(NA, 51)
st.names <- unique(polls08$state)

for (i in 1:51) {
  state.data <- subset(polls08, subset = (state == st.names[i]))
  latest <- subset(state.data, DaysToElection == min(DaysToElection))
  poll.pred[i] <- mean(latest$margin)
}
```

```{r}
errors <- pres08$margin - poll.pred

names(errors) <- st.names
mean(errors)
```

```{r}
sqrt(mean(errors^2))
```

```{r}
hist(errors, freq = FALSE, ylim = c(0, 0.08), main = "Poll prediction error", xlab = "Error in prediction margin for Obama (precentage points)")
abline(v = mean(errors), lty = "dashed", col = "blue")
text(x = -7, y = 0.08, "average error", col = "blue")
```

```{r}
plot(poll.pred, pres08$margin, type = "n", main = "", xlab = "Poll results", xlim = c(-40, 90), ylim = c(-40, 90), ylab = "Actual election results")

text(x = poll.pred, y = pres08$margin, labels = pres08$state, col = "blue")
abline(a = 0, b = 1, lty = "dashed")
abline(v = 0)
abline(h = 0)
```

```{r}
pres08$state[sign(poll.pred) != sign(pres08$margin)]
```

```{r}
pres08$margin[sign(poll.pred) != sign(pres08$margin)]
```

```{r}
sum(pres08$EV[pres08$margin > 0])
```

```{r}
sum(pres08$EV[poll.pred > 0])
```

```{r}
pollsUS08 <- read.csv("pollsUS08.csv")
```

```{r}
pollsUS08$middate <- as.Date(pollsUS08$middate)
pollsUS08$DaysToElection <- as.Date("2008-11-04") - pollsUS08$middate

Obama.pred <- McCain.pred <- rep(NA, 90)
```

```{r}
for (i in 1:90) {
  week.data <- subset(pollsUS08, subset = ((DaysToElection <= (90 - i + 7)) & (DaysToElection > (90 - i))))
  Obama.pred[i] <- mean(week.data$Obama)
  McCain.pred[i] <- mean(week.data$McCain)
}
```

```{r}
plot(90:1, Obama.pred, type = "b", xlim = c(90, 0), ylim = c(40, 60), col = "blue", xlab = "Days to the election", ylab = "Support for candidate (percentage points)")
lines(90:1, McCain.pred, type = "b", col = "red")
points(0, 52.93, pch = 19, col = "blue")
points(0, 45.65, pch = 19, col = "red")
abline(v = 0)
text(80, 48, "Obama", col = "blue")
text(80, 41, "McCain", col = "red")
```


